apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
    visualize: "true"
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
        version: v1
        visualize: "true"
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - name: zipkin
          containerPort: 9411