apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      name: grpc
      targetPort: 9092
  selector:
    app: chat-service